# Generated by Django 4.0.4 on 2022-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('team_leader', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=20, null=True)),
                ('stack', models.CharField(max_length=50, null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('resource_status', models.CharField(max_length=50, null=True)),
                ('date_of_joining', models.CharField(max_length=50, null=True)),
                ('profile_link', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
