# Generated by Django 4.0.4 on 2022-05-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bench', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
